FROM ubuntu:20.04
RUN apt update -y
RUN apt install -y openjdk-11-jdk
RUN mkdir -p /u02/applications/
COPY target/tokengenerator-1.0.jar /u02/applications
CMD java -cp /u02/applications/tokengenerator-1.0.jar com.tg.service.TokenGeneratorService
